@baseUrl = https://m1p10mean.onrender.com/

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVm9uankiLCJ1c2VySWQiOiI2M2M1MGNmNmQ1ODYzMjExNzY4MWQ1MTYiLCJpYXQiOjE2NzM4NzQxMTIsImV4cCI6MTY3Mzg3NzcxMn0.DsaSD0FJt9FttRwMKfuds6nTHmJfgwCUmap1z6t0Ifo


###
POST {{baseUrl}}/auth/inscription HTTP/1.1
Content-Type: application/json

{
    "name":"Vonjy",
    "email":"vonjy@gmail.com",
    "password":"123456",
    "role":"Client"
}
###
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"vonjy@gmail.com",
    "password":"123456"
}


###

GET {{baseUrl}}/auth/allUser?id=2 HTTP/1.1
Authorization: Bearer {{token}}